feat: hide 2U specific fields
openedx/frontend-app-publisher pull request #797
Opened 2022-11-22 10:56 UTC by uzairr

Few 2U specific fields are appearing for all types of the course(s) which is creating confusion for the partners.Due to this change, 2U fields would only be displayed for 2U courses

PROD-3032

2022-11-22 15:30 UTC, arbrandes requested changes
Can we please make this a configurable setting, instead of making hard-coded references to 2U in the code?

2022-11-23 08:28 UTC, Ali-D-Akbar approved these changes
Do we have a snapshot where these override fields appear? 
If yes then it looks good to me.

2022-11-23 12:41 UTC, AliAdnanSohail approved these changes

2022-11-23 13:30 UTC, arbrandes requested changes
Still think we can make this more generic.  Thanks for bearing with me.

2022-11-23 13:30 UTC, arbrandes commented on src/components/EditCoursePage/EditCourseForm.jsx
> +  filterCourseTypes2U(courseType) {
If we remove "2U" from the object and parameter names we can avoid confusion in the future, making this a truly generic feature.

```suggestion
  filterCourseTypes(courseType) {
```

2022-11-23 13:30 UTC, arbrandes commented on src/components/EditCoursePage/EditCourseForm.jsx
> +    const courseTypes2U = courseTypeOptions.filter(this.filterCourseTypes2U);
```suggestion
    const courseTypesToFilter = courseTypeOptions.filter(this.filterCourseTypes);
```

2022-11-23 13:30 UTC, arbrandes commented on src/components/EditCoursePage/EditCourseForm.jsx
> +            {courseTypes2U?.length > 0 && (
```suggestion
            {courseTypesToFilter?.length > 0 && (
```

2022-11-23 13:30 UTC, arbrandes commented on .env
> +IDENTIFIER_2U='2U'
Let's rename this as well, and remove the "2U" default setting which does not make sense for all use cases.

```suggestion
COURSE_TYPE_FILTER=''
```

2022-11-23 13:30 UTC, arbrandes commented on .env.development
> +IDENTIFIER_2U='2U'
```suggestion
COURSE_TYPE_FILTER=''
```

2022-11-23 13:30 UTC, arbrandes commented on src/components/EditCoursePage/EditCourseForm.jsx
> +    return courseType.label.includes(getConfig().IDENTIFIER_2U);
```suggestion
    return courseType.label.includes(getConfig().COURSE_TYPE_FILTER);
```

2022-11-23 13:30 UTC, arbrandes commented on .env.test
> +IDENTIFIER_2U='2U'
```suggestion
COURSE_TYPE_FILTER=''
```

2022-11-23 13:33 UTC, ansabgillani approved these changes

2023-11-01 06:41 UTC, closed without merging